development:
  adapter: postgresql
  encoding: unicode
  database: <DATABASE_NAME>
  pool: 5
  username: <username>
  password: <password>
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost
